Repository cri-o/ocicni, pull requests merged in 2019-07, with the labels that each got.

#39 Support dual-stack CHECK Results when cached result is missing
  pkg/ocicni/ocicni.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#48 vendor: update containernetworking/cni for config caching
  go.mod
  go.sum
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#43 ocicni: ensure returned CHECK results are the same CNIVersion as config
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#50 Update the internal localhost CNI to v0.3.1
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
