Repository cri-o/ocicni, pull requests merged in 2019-09, with the labels that each got.

#56 Delete/Check sandboxes from cached config when available
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
  pkg/ocicni/types.go
  tools/ocicnitool/ocicnitool.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#57 Avoid to overwrite network in loadNetworks()
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#59 ocicni: find networks to delete from cache
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#58 reload default CNI network name real-time if it is not assigned in initialization
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#60 bump up libcni to support cache IfName and NetworkName
  go.mod
  go.sum
  pkg/ocicni/ocicni_test.go
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#61 ocicni: add support of specifying static MACs
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
  pkg/ocicni/types.go
Labels: approved, dco-signoff: yes, lgtm, size/M
