Repository cri-o/ocicni, pull requests merged in 2019-04, with the labels that each got.

#32 Add approvers to OWNERS
  OWNERS
Labels: dco-signoff: yes, size/XS

#28 Add bandwidth plugin support
  pkg/ocicni/ocicni.go
  pkg/ocicni/types.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#35 Move pod-specific configuration to RuntimeConfig
  pkg/ocicni/ocicni.go
  pkg/ocicni/types.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#34 support podCIDR in cniNetworkPlugin
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
  pkg/ocicni/types.go
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/L
