Repository cri-o/ocicni, pull requests merged in 2021-06, with the labels that each got.

#91 ocicni: pass a Pod UID down to CNI plugins as K8S_POD_UID
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
  pkg/ocicni/types.go
Labels: approved, dco-signoff: yes, lgtm

#92 Add option to disable the use of inotify
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#93 [cni-0.x] Add option to disable the use of inotify
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#94 ocicni: pass a Pod UID down to CNI plugins as K8S_POD_UID
  pkg/ocicni/ocicni.go
  pkg/ocicni/ocicni_test.go
  pkg/ocicni/types.go
Labels: approved, dco-signoff: yes
